Repository ZupIT/ritchie-server, pull requests merged in 2020-04, with the labels that each got.

#4 [Enhancement] Contributing file
  CONTRIBUTING.md
  README.md
  docs/img/git-branchs.png
Labels: enhancement

#12 Circleci project setup
  .circleci/config.yml
  .gitignore
  Makefile
  README.md
  credentials.sh
  docker-compose-ci.yml
  go.mod
  go.sum
  registry.sh
  run-tests-ci.sh
  version.sh
Labels: feature

#5 [Enhancement] Contributing file
  CONTRIBUTING.md
  README.md
Labels: feature

#16 Feature/code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, feature
